### PR TITLE
Fix for negative values encoded in f8.8

### PR DESCRIPTION
**Pull request by SebuZet**
The problem was with storing negative number in unsigned int variable. eg. value 0xff00 encoded as fixed float 8.8 was decoded to 16777215 *C instead of -1. Now it is decoded correctly.

### CODE REVIEW

**Comment by SebuZet** [comment]
The problem was with storing begative number in unsigned int variable. eg. value 0xff00 encoded as fixed float 8.8 was decoded as 16777215 *C. Not ot is decoded correctly.

**Comment by ov1d1u** [comment]
Thanks! I'm gonna test this for a few days to see if something goes wrong and if it behaves well I'll merge it in the main branch.

**Comment by SebuZet** [comment]
Sure, totally understand. It is working on my device about a week. I had very strange readings when outside temp went below zero.

**Comment by ov1d1u** [comment]
Seems to work well, so I'm going to merge this. Thanks again for your contribution.

**Pull request merged**
